name: Update Islamic Date

on:
  schedule:
    - cron: '0 1 * * *'  # Runs everyday at 4am SAST
  workflow_dispatch:

permissions:
  contents: write  # Gives the action permission to push commits

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install beautifulsoup4 selenium

      - name: Run scraper
        run: python scrape_islamic.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add index.html
          git commit -m "Updated islamid date" || echo "No changes to commit"
          git push
